server {
    #listen 443 ssl;
    listen 80;
    server_name SERVER_NAME_PLACEHOLDER;

    #ssl_protocols TLSv1.3;
    # ruta a los certificados que creamos en el entrypoint, aunque esto pasa antes (?)
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    location / {
        proxy_pass http://wordpress:80; # Envía la petición al contenedor wordpress
        include proxy_params;             # Configuración estándar de cabeceras
    
    }
}


#Opción A (Proxy Inverso - Puerto 80): Si tu contenedor de WordPress tiene un servidor web dentro (como Apache o Nginx), usas proxy_pass http://wordpress:80;.

#Opción B (FastCGI - Puerto 9000): Si usas la imagen oficial wordpress:php-fpm (que es lo que suele pedir el sujeto de 42), no hay servidor web en WordPress. Solo hay un procesador de PHP escuchando en el puerto 9000.


# #!/bin/bash

# # 1. Salir inmediatamente si hay un error
# set -e

# # 2. Verificar si la variable USER está definida
# if [ -z "$USER" ]; then
#     echo "ERROR: La variable USER no está definida en el entorno."
#     echo "Revisa tu archivo .env y el docker-compose.yml"
#     exit 1
# fi

# # 3. Si llegamos aquí, USER existe. Generamos el certificado.
# echo "Generando certificado para: ${USER}.42.fr"

# mkdir -p /etc/nginx/ssl

# openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
#     -keyout /etc/nginx/ssl/inception.key \
#     -out /etc/nginx/ssl/inception.crt \
#     -subj "/C=ES/ST=Malaga/L=Malaga/O=42/OU=Inception/CN=${USER}.42.fr"

# # 4. Lanzar Nginx
# exec nginx -g "daemon off;"