services:
    mariadb:
        image: mariadb:latest
        #build:
            #context: ./requirements/mariadb
            #dockerfile: Dockerfile
        container_name: mariadb
        env_file: 
            - ./requirements/mariadb/.env
        networks:
            - inception_network_db
        volumes:
            - db_data:/var/lib/mysql
        restart: always

    wordpress:
        image: wordpress:latest
        #build:
            #context: ./requirements/wordpress
            #dockerfile: Dockerfile
        container_name: wordpress
        env_file:
            - ./requirements/wordpress/.env
        networks:
            - inception_network_nginx
            - inception_network_db
        volumes: 
            - wp_data:/var/www/html
        restart: always

    nginx:
        #image: nginx:latest
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        container_name: nginx
        env_file:
            - ./requirements/nginx/.env
        networks:
            - inception_network_nginx
        #command: [nginx-debug, '-g', 'daemon off;']
        ports:
            - "80:80" #port bind(capa7 OSI) / forwarding (capa4)
        volumes: 
            #- nginx_conf:/etc/nginx
            - ./requirements/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro #bind volume
        restart: always

networks:
    inception_network_nginx:
    inception_network_db:
volumes:
    db_data:
        name: mariadb_data
    wp_data:
    nginx_conf: 



# docker run -d 
#   --name mariadb 
#   --network inception_net 
#   -e MARIADB_ROOT_PASSWORD=root123 
#   -e MARIADB_DATABASE=wordpress_db 
#   -e MARIADB_USER=wp_user 
#   -e MARIADB_PASSWORD=wp_pass 
#   mariadb:latest

# docker run -d 
#   --name nginx 
#   --network inception_net 
#   -p 80:80 
#   -v $(pwd)/default.conf:/etc/nginx/conf.d/default.conf:ro 
#   nginx:latest
  
# docker run -d 
#   --name wordpress 
#   --network inception_net 
#   -e WORDPRESS_DB_HOST=mariadb 
#   -e WORDPRESS_DB_USER=wp_user 
#   -e WORDPRESS_DB_PASSWORD=wp_pass 
#   -e WORDPRESS_DB_NAME=wordpress_db 
#   wordpress:latest
