server {
    listen 80; # Por ahora usamos 80 para no liarnos con certificados SSL en el portátil
    server_name localhost;

    location / {
        proxy_pass http://wordpress:80; # Aquí usamos el nombre del contenedor de WordPress
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
